#!/bin/bash
#
# Compile script for Ice kernel
# Copyright (C) 2020-2021 Adithya R.

# Work Path
WORK="${HOME}/work"

# Kernel Folder Name - Don't change
KERNEL="myKernel"

# Kernel Source Path
KERNEL_SRC="${WORK}/${KERNEL}"

# Kernel Source - Recommend to replace the URL by your target Kernel Source and Branch (even if its main or master, put it).
KERNEL_SOURCE_URL="https://github.com/cd-Seraph/kernel_realme_ice"
KERNEL_BRANCH="RMX3461"

# Clang URL - Change the version, depends on your kernel source.
CLANG_TAR_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android13-release/clang-r450784d.tar.gz"

# Others - Change this to your preference.
ANYKERNEL_GIT="https://github.com/cd-Seraph/AnyKernel3.git"
ZIPNAME="Kernel-ICE-by-Seraph.zip"

TC_DIR="${WORK}/clang"
AK3_DIR="$KERNEL_SRC/AnyKernel3"
DEFCONFIG="vendor/lahaina-qgki_defconfig"
MAKE_PARAMS="O=out ARCH=arm64 CC=clang CROSS_COMPILE=$TC_DIR/bin/llvm- LLVM=1 LLVM_IAS=1 \
	CLANG_TRIPLE=aarch64-linux-gnu-"


# Prepare Directory
mkdir -p "${WORK}"
cd "${WORK}" || exit 1

if [ ! -d clang ]; then mkdir clang && curl -Lsq "${CLANG_TAR_URL}" -o clang.tgz && tar -xzf clang.tgz -C clang; fi
[ ! -d myKernel ] && git clone --depth=1 "${KERNEL_SOURCE_URL}" -b ${KERNEL_BRANCH} ${KERNEL}

# Setting Toolchain Path
export PATH="${TC_DIR}/bin:/bin"

SECONDS=0 # builtin bash timer

# Preparing Build Process
cd "${KERNEL_SRC}" || exit 1

# Integrating KernelSU
curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -


if [[ $1 = "-r" || $1 = "--regen" ]]; then
	make $MAKE_PARAMS $DEFCONFIG savedefconfig
	cp out/defconfig arch/arm64/configs/$DEFCONFIG
	echo -e "\nSuccessfully regenerated defconfig at $DEFCONFIG"
	exit
fi

if [[ $1 = "-c" || $1 = "--clean" ]]; then
	rm -rf out
	echo "Cleaned output folder"
fi

mkdir -p out
make $MAKE_PARAMS $DEFCONFIG

echo -e "\nStarting compilation...\n"
make -j$(nproc --all) $MAKE_PARAMS || exit $?
make -j$(nproc --all) $MAKE_PARAMS INSTALL_MOD_PATH=modules INSTALL_MOD_STRIP=1 modules_install

kernel="out/arch/arm64/boot/Image"
dtb="out/arch/arm64/boot/dts/vendor/oplus_7325/yupik.dtb"
dtbo="out/arch/arm64/boot/dts/vendor/oplus_7325/yupik-21643-overlay.dtbo"

if [ -f "$kernel" ] && [ -f "$dtb" ] && [ -f "$dtbo" ]; then
	echo -e "\nKernel compiled succesfully! Zipping up...\n"

        git clone $ANYKERNEL_GIT AnyKernel3
	
	cp $kernel AnyKernel3
	cp $dtb AnyKernel3/dtb
	python2 scripts/dtc/libfdt/mkdtboimg.py create AnyKernel3/dtbo.img --page_size=4096 $dtbo
	cd AnyKernel3
	zip -r9 "../$ZIPNAME" * -x .git README.md *placeholder
	cd ..
	echo -e "\nCompleted in $((SECONDS / 60)) minute(s) and $((SECONDS % 60)) second(s) !"
	echo "Zip: $ZIPNAME"
else
	echo -e "\nCompilation failed!"
	exit 1
fi

